#!/usr/bin/env python

import turtle
from turtle import *

def drawHil(t, order, size):
    if order == 0:
        t.forward(size)
    else:
        t.left(90)
        drawHil(t, order-1, size/3)
        t.right(90)
        drawHil(t, order-1, size/3)
        drawHil(t, order-1, size/3) 
        t.right(90)
        drawHil(t, order-1, size/3)
        t.left(90)

def drawHil2(t, order, size):
    drawHil(t, order, size)
    t.right(90)
    drawHil(t, order, size)
    t.right(90)
    drawHil(t, order, size)
    t.right(90)
    drawHil(t, order, size)

def drawoct(t, order, size):
    drawHil(t, order, size)
    t.right(60)
    drawHil(t, order, size)
    t.right(60)
    drawHil(t, order, size)
    t.right(60)
    drawHil(t, order, size)
    t.right(60)
    drawHil(t, order, size)
    t.right(60)
    drawHil(t, order, size)

screen = Screen()
screen.setup(640,640)
screen.title('Hilbert Curve Fractal')
screen.bgcolor('#333333')
t = turtle.Turtle()
t.hideturtle()
t.speed(0)
t.color('#CC3333')
t2 = turtle.Turtle()
t2.hideturtle()
t2.speed(0)
t2.color('#FF8243')
t3 = turtle.Turtle()
t3.hideturtle()
t3.speed(0)
t3.color('#DF00FF')

drawHil2(t2, 4, 400)
drawHil2(t2, 4, 400)
drawHil2(t2, 4, 400)
drawHil2(t2, 4, 400)
drawoct(t3, 4,  400)
drawoct(t3, 4,  400)
drawoct(t3, 4,  400)
drawoct(t3, 4,  400)
drawoct(t3, 4,  400)
drawoct(t3, 4,  400)
drawHil2(t, 4, 700)
drawHil2(t, 4, 700)
drawHil2(t, 4, 700)
drawHil2(t, 4, 700)
turtle.mainloop()



